### ISSUE TITLE
[CRASH] - Constantly crashing with multiple libraries containing over a million music tracks.

### ISSUE THREAD

**Issue by digitclockguy** [eddyizm/tempus#208]
## Description

I open up Tempus app to navigate to smart playlist or anywhere else and it crashes at random times.

## Steps to Reproduce.

1. Create a user that has access to multiple libraries totalling over a million music files on a desktop website.
2. Open up app an Android, try to navigate to a playlist., or play around with the settings.
3. Play some music.

## Environment
 - Android device: Samsung Galaxy S24 Ultra
 - Android OS version: 16
 - App version: 4.0.7
 - App variant: google play services
 - Other relevant details: connected to server via tailscale on mobile network.

I could not find crash log.

It crashes very frequently.

Not too sure if this app can handle a loggin in user having access to over a million of music files even using smart playlist with only 100 entries.

**Comment by eddyizm** [comment]
HI @digitclockguy, 
I have 1k track playlists that work fine on my end, however I have nowhere near that amount of tracks in total. 

I don't know how I could test this without access to a server with a large amount of tracks. 

It is very likely that beyond there being performance issues with the large library, most of the crashes I have seen/fixed here are related to api responses missing data or the app not handling nulls correctly. 
That being said, I need to be able to recreate the crash to see what that error is. 

As far as collecting the crash logs, that is a little tricky. You would either have to enable developer options and go through those hoops.

The other way is to install ADB and get them there `adb logcat -d > crash_log.txt` which also requires developer options. 

I could get you a debug apk to get more info but would also need to collect logs in the same way.

**Comment by pca006132** [comment]
This is interesting, I don't think there is a single API that queries all songs?

Btw, what is a smart playlist?

I think it will also be helpful to know which server that is, e.g. navidrome or something. So we can check for API compatibility, cuz often times the APIs are not very compatible...

**Comment by pca006132** [comment]
Oh, getting the artists may be able to crash the app when there are millions of artists...

**Comment by eddyizm** [comment]
> This is interesting, I don't think there is a single API that queries all songs?  

there is definitely not, related -  an all songs section is on the map that we will need to figure a work around there...

> Btw, what is a smart playlist?  

I think this is a new navidrome thing - which I don't think I want to support if it is not a standard subsonic or open subsonic api endpoint/feature

**Comment by digitclockguy** [comment]
Sorry I didn't realize that this app connects to more types of opensubsonic compatible servers than Navidrome. But that is what I used. I did forget to tell. I'll try a different server software w/o the features to see if I run into the same problem.

I did have a work around solution by creating different accounts on the same server and tie it only to those specific libraries which is more stable than what I had previously.

**Comment by pca006132** [comment]
Can you provide the precise steps to reproduce the issue? The current description is not very precise, basically impossible to diagnose without access to the server.

**Comment by digitclockguy** [comment]
I'll try eventhough I'm posting from a smartphone. I can't copy paste commands right now because I am out of town.

What I did:
1. Gathered up all the music files I obtained from various sources and placed them in different folders. I have three major seperate folders containing 200-500k files each.
2. I installed docker and downloaded the Navidrome(0.58.0) via the docker pull command container.
3. I created the Navidrome instance with this command:
```
docker run -d \
--name navidrome-server \
--restart=unless-stopped \
--user (id −u):(id -g) \
-v /home/username/.navidrome/music:/music \
-v /mnt/disk/mymegacollection1:/musdir1 \
-v /mnt/disk/mymegacollection2:/musdir2 \
-v /mnt/disk/mymegacollection3:/musdir3 \
-v /home/username/.navidrome/data:/data \
-p 4533:4533 \
-e ND_LOGLEVEL=info \
-e ND_ENABLETRANSCODINGCONFIG=false \
-e ND_SMARTPLAYLISTREFRESHDELAY=60s \
-e ND_ENABLEMEDIAFILECOVERART=true \
deluan/navidrome:0.58.0
``` 
4. I added the libraries within the Navidrome web software as it took hours to scan all the total files.
5. I created a user and enabled all libraries.
6. Loaded up Tempus, and logged in with that user.
7. Tried to play some music, navigated through the music library without accessing the playlists, play some music, go back looknfor another, ends up crashing randomly.

I did use smart playlists(which is a Navidrome thing), but this time I also did try to navigate through the music library without going through the Playlist and still same result.

I hope this is precise enough to my knowledge.

**Comment by pca006132** [comment]
The part that needs to be specific is step 7. It is hard to know what caused the crash via such a description. E.g. did you browse by genre? artists? albums?

**Comment by digitclockguy** [comment]
I'm trying to reproduce the crash bug right now. As I leave the app idle or click on an album on the front page to play music and leave it idle for a while, I don't experience any crashes at first. But the more I use the interface to browse different librariea by searching music via random keywords, or clicking on genres to list tracks to play, or browse around in the options, eventually I will experience a crash.

The only options I have on is show audio quality, and prioritize server transcode settings. The artwork cache and image resolution is also set to high. The cache streaming size is 256MB.

I'll play around with the settings to see if the results are thr same or not.

Update: Still crashes even with Medium settings, limit mobile data settings and increased cache streaming increased up to 512MB.

**Comment by Neogrey** [comment]
I'm not sure if it's the same bug, but when I scroll through my large playlist (currently 1208 tracks) after a while, the app slows down, freezes, and eventually crashes completely while scrolling.  It's impossible for me to reach the end of the playlist.

I can reproduce this on my Pixel 9 and Pixel Tablet (both running GrapheneOS and the degoogled Tempus version).

adb logcat -d:

[crash_log.txt](https://github.com/user-attachments/files/23270081/crash_log.txt)

@eddyizm if you need any further information, feel free to ask ;).

**Comment by pca006132** [comment]
> I'm not sure if it's the same bug, but when I scroll through my large playlist (currently 1208 tracks) after a while, the app slows down, freezes, and eventually crashes completely while scrolling. It's impossible for me to reach the end of the playlist.
> 
> I can reproduce this on my Pixel 9 and Pixel Tablet (both running GrapheneOS and the degoogled Tempus version).
> 
> adb logcat -d:
> 
> [crash_log.txt](https://github.com/user-attachments/files/23270081/crash_log.txt)
> 
> [@eddyizm](https://github.com/eddyizm) if you need any further information, feel free to ask ;).

Sounds like another performance bug related to improper recycler view usage. Should not be hard to fix.

**Comment by pca006132** [comment]
> I'm trying to reproduce the crash bug right now. As I leave the app idle or click on an album on the front page to play music and leave it idle for a while, I don't experience any crashes at first. But the more I use the interface to browse different librariea by searching music via random keywords, or clicking on genres to list tracks to play, or browse around in the options, eventually I will experience a crash.
> 
> The only options I have on is show audio quality, and prioritize server transcode settings. The artwork cache and image resolution is also set to high. The cache streaming size is 256MB.
> 
> I'll play around with the settings to see if the results are thr same or not.
> 
> Update: Still crashes even with Medium settings, limit mobile data settings and increased cache streaming increased up to 512MB.

Maybe it is killed by the oom killer or something? I am not familiar with android to know the oom behavior.

**Comment by pca006132** [comment]
> I'm not sure if it's the same bug, but when I scroll through my large playlist (currently 1208 tracks) after a while, the app slows down, freezes, and eventually crashes completely while scrolling. It's impossible for me to reach the end of the playlist.
> 
> I can reproduce this on my Pixel 9 and Pixel Tablet (both running GrapheneOS and the degoogled Tempus version).
> 
> adb logcat -d:
> 
> [crash_log.txt](https://github.com/user-attachments/files/23270081/crash_log.txt)
> 
> [@eddyizm](https://github.com/eddyizm) if you need any further information, feel free to ask ;).

Are you sure it is the playlist feature? I looked at it, it seems that playlist and player queue are fine with a large amount of data (I tested with 400, if things are that bad, 400 should be laggy when run in an emulator). Things like artist page is still buggy, but I cannot find anything else (other than the download tab, which is now fixed).

**Comment by pca006132** [comment]
Or if these are memory usage related issues, maybe we should limit the recycler view cache size.

**Comment by Neogrey** [comment]
It definitely happens when you scroll quickly through the playlist. 

Maybe I'm completely wrong, but my music is tagged with high-res artwork (e.g., 3000x3000), and Tempus seems to try to download it while I'm scrolling (?). Perhaps it would make sense to scale the covers down to a lower resolution on the server side for the playlist. This seems to work if you add for e.g. &size=500 to the end of the getCoverArt URL and then the scaled image is returned.

**Comment by pca006132** [comment]
1. It seems to me that Glide will automatically downsample the image to match the image view dimension, at least I hope so. So high resolution images should not be a big issue?
2. I managed to trigger a crash by opening the playlist, and repeated opening the playlist 3 times without destroying a view (with #219). It seems to me that this is something related to memory usage. Should probably do a memory profiling to see what is going on. I only started writing Android stuff two days ago to fix bugs here, so I have completely no idea how memory reclamation is done with recycler view...
3. @eddyizm mentioned above that he had playlists with 1k tracks without issue?

**Comment by eddyizm** [comment]
> I'm not sure if it's the same bug, but when I scroll through my large playlist (currently 1208 tracks) after a while, the app slows down, freezes, and eventually crashes completely while scrolling. It's impossible for me to reach the end of the playlist.
> 
> I can reproduce this on my Pixel 9 and Pixel Tablet (both running GrapheneOS and the degoogled Tempus version).
> 
> adb logcat -d:
> 
> [crash_log.txt](https://github.com/user-attachments/files/23270081/crash_log.txt)
> 
> [@eddyizm](https://github.com/eddyizm) if you need any further information, feel free to ask ;).

I did realize that even though I am able to load and play 1k playlist, the way I use it, I generally don't scroll too much and just let it fly. I do all my organization on the backend/web interface and then just play on the go so it seems that I probably never hit the bugs you guys are hitting as mentioned.

**Comment by vodkapmp** [comment]
> I think this is a new navidrome thing - which I don't think I want to support if it is not a standard subsonic or open subsonic api endpoint/feature

The smart playlists don't really have anything to say for the api. It's just a function that generates a playlist automatically for you. See issue [#1417](https://github.com/navidrome/navidrome/issues/1417) from 2021 over at the navidrome repo

This is my main reason for using navidrome, as I can make rules based playlists that automatically update when new songs are added.
I like having large playlists of entire genres, or multiple genres that I keep on shuffle for long playback sessions where I don't want to keep picking new music (traveling for 10+ hours is a regular occurrence in my life)

Both Tempo and Tempus crashes a lot for me when trying to offline a large playlists, I can however open and interact with big playlists without issues, even one I have which is 8000 songs works just fine for opening, playing back, and even shuffling.
My issue is trying to offline one of these playlists, if I tell Tempus to offline a playlist with 2000 songs, the app will continuously crash and become unusable if I don't keep pressing "wait" on the crash dialogue until it's done downloading (which takes a while with 2000+ songs)

**Comment by pca006132** [comment]
@vodkapmp 
There are a lot of (to-be-merged) changes to address these performance issues. If you are willing to compile them yourself, maybe you can try and see if that solves your issues.

**Comment by pca006132** [comment]
can you try the latest development branch to see if this is fixed?

**Comment by vodkapmp** [comment]
I've not got a setup where I could compile this myself available right now. And there doesn't seem to be any build artifacts under actions either.

Is the apk available anywhere that I just can't find?

**Comment by pca006132** [comment]
should probably wait for a release, @eddyizm said he will do it this week.

**Comment by eddyizm** [comment]
fix released https://github.com/eddyizm/tempus/releases/tag/v4.1.0 - Let me know if this helps solve this issue so we can close this ticket.

**Comment by digitclockguy** [comment]
So I logged in to an account with access to over a million music tracks, navigating through the library by clicking random albums, searching via keywords, app still crashes on me.

If fixing this is not possible, I can settle with creating multiple accounts for different libraries as it appears to be stable for me atm.

**Comment by eddyizm** [comment]
> So I logged in to an account with access to over a million music tracks, navigating through the library by clicking random albums, searching via keywords, app still crashes on me.
> 
> If fixing this is not possible, I can settle with creating multiple accounts for different libraries as it appears to be stable for me atm.

The challenge me is to be able to recreate this locally while the debugger is connected to get the right thread to pull at. Otherwise we are guessing at which performance problem might be causing it. 

Would it be possible to access one of those accounts to test for a limited time? (not today, I want to be ready to tackle it so we can decide when)

**Comment by vodkapmp** [comment]
I don't have access to a massive library like this, but I do still get constant crashes when trying to download my 2000 song playlist, as soon as I start the download the app starts crashing every few seconds (it doesn't die fully and it does keep downloading)
It does seem to happen not as often with these changes, it went from giving the popup saying it's not responding every 1-1.5s, to every 5-6s instead.

Maybe creating a playlist with 2000 songs and starting a download might let you replicate at least this issue which might point in the right direction for the issues with massive libraries?

**Comment by eddyizm** [comment]
> Maybe creating a playlist with 2000 songs and starting a download might let you replicate at least this issue which might point in the right direction for the issues with massive libraries?

That's a good idea. maybe even upping it to 4k or something large, i have enough tracks for that no problem. I should be able to recreate it since everyone else is crash at 1k plus, it will never need to get to 1 million :-)

**Comment by pca006132** [comment]
For the record, I have not optimized download, I just optimized the views. I have not optimized seaech either.

But the question here is: does it still crash when you scroll through playlists and play them? i.e., does it solve the problem you *originally* reported?

We should list the things that have problems, solve them one by one, and check if things are solved.

**Comment by pca006132** [comment]
@vodkapmp I tried optimizing the download. It turns the DAO is a mess: a lot of things block on the main thread. I tried changing stuff there, and got https://github.com/pca006132/tempus/tree/fix-cache-artwork (which is a bit huge for cleanup for now).

~~You can see if you want to compile it from source or download one precompiled and signed by me in https://drive.google.com/file/d/17KOtd-P_0evhj_C-o5dl0G2i-7g9ksqt/view?usp=sharing.

Note that it is very likely that there are other crashes, or maybe I increased the number of potential crashes. This just removed the thread join behaviors and thrown everything to background executors.~~

ok it is crashing for fresh install, let me see..

**Comment by pca006132** [comment]
@vodkapmp should be fixed now

**Comment by vodkapmp** [comment]
@pca006132 

I have no crashes while downloading my 2000+ song playlists with this version.
No crashes while downloading and hopping around to various places of the app, shuffling other large playlists, etc.

My library only has around ~30k tracks though, so nowhere near what OP has.

**Comment by pca006132** [comment]
@vodkapmp is there anything in the ui that feels slow/sluggish? other than the search results and artist page, those are known issues.

**Comment by vodkapmp** [comment]
@pca006132 UI seems to be good, not much sluggishness or anything.
Clicking on a large playlist, for example this 2000+ song playlist I've been testing with takes a while for it to load, around 5s. (varies between around 4s and 7s)
7000 track playlist, loads in roughly the same amount of time.
1000 track playlist, loads in at around 2-3 seconds.
200 track playlist, loads just about instantly.

**Comment by pca006132** [comment]
Loading speed is not a priority for now, if it doesn't make the UI unresponsive. There are too many things that can be optimized, so we should do it one by one.

**Comment by pca006132** [comment]
@vodkapmp just found another silly bug, the drive link is updated (if you really want to use that). And btw, I would suggest you to not rely on the apk I posted cuz I am changing and breaking things pretty quickly...

**Comment by vodkapmp** [comment]
I'm gonna wait for an official release to actually use, but I am happy to install that to help with any testing.
I use Symfonium as my goto app anyway, just here hoping for a good FOSS alternative to replace it at some point.

**Comment by SuperGripM** [comment]
Adding to this - I am experiencing complete UI freezes (although tracks keep playing and new tracks are played as expected!) on a playlist that has just over 500 songs. The freeze only happens if I leave the app, then go back to it. As long as I stay in the app, it doesn't happen.
The widget also stays stuck on the first song of the playlist and the app causes SystemUI to crash on occasion. If I try to stop the app (by swiping up on the pager menu), it refuses to do so. After a few seconds, the OS will tell me the app isn't responding and offer to kill it.

Logs are attached. (Pixel 7, GrapheneOS 16, degoogled variant). The logs are from 4.2, but I've tried 4.2.4 to the same effect.

[Tempus log 009587193889.txt](https://github.com/user-attachments/files/23568487/Tempus.log.009587193889.txt)

**Comment by pca006132** [comment]
@SuperGripM there are already fixes that are waiting to be upstreamed.

**Comment by SuperGripM** [comment]
Mad! Can't wait to test.

**Comment by eddyizm** [comment]
@SuperGripM We will have a debug apk out to test soon I think, before making these major changes in the main release.

**Comment by tvillega** [comment]
Hi @digitclockguy, on the [latest pre-release](https://github.com/eddyizm/tempus/releases/tag/v4.16.2-dev) we added a crash landing page.

If you can replicate the crash, that screen will provide useful logs to better understand what went wrong.
