### ISSUE TITLE
[Feature Request] - Compatibility Android Auto

### ISSUE THREAD

**Issue by georgeschris01** [eddyizm/tempus#54]
Will this version be available on Android Auto? I read that CappielloAntonio's version was, but I admit I downloaded that version directly.

So it's possible it is, but it doesn't appear on my Android Auto.

Thank you for your work :-D

**Comment by eddyizm** [comment]
Hi @georgeschris01 This version includes everything that CappielloAntonio - it builds on top of it. What version are you on? The last version on from the old repo was 3.9.0 - The releases here start at 3.10.0 and I just released 3.13.0 yesterday. Android auto has not been removed and should work. 

Admittedly, I don't have/use that feature and am working to figure out how to get the emulator working on my laptop to test.

**Comment by georgeschris01** [comment]
Hello, I installed the latest version and I still don't have Tempo on Android Auto. I have Google Android Auto version 14.7.652684.

I'm in no rush, take your time ;-)

**Comment by eddyizm** [comment]
Hi @georgeschris01 Can you verify the version number of Tempo in the Settings? Scroll to the bottom. Also, where did you install from? With my fork I am only distributing releases from github releases.

**Comment by Londoneye02** [comment]
Same problem here. downloaded from Github

**Comment by eddyizm** [comment]
> Same problem here. downloaded from Github

Hi @Londoneye02 ,
Can you verify the tempo version? 

This feature was working before I forked it, and as far as I know, no code has been removed regarding this feature. 

So if it's broken then I must have done something at the first fork.

**Comment by jaime-grj** [comment]
You have to enable Android Auto developer options, which are different from actual Android dev options. Then you have to enable "Unknown sources" in Android Auto, otherwise the app won't appear as it isn't downloaded from Play Store.

**Comment by eddyizm** [comment]
@jaime-grj Thanks for the clarification! I think I am going to create a `USAGE.md`  or something to similar to link from the `README.md` for more details on how the application works. This would be perfect for that. 
If we have any screenshots, I plan on getting an emulator for android auto to work since I don't have a way to test/see this myself.

**Comment by georgeschris01** [comment]
Hello everyone, I'll test this tomorrow and let you know.

Thanks for the information.

**Comment by georgeschris01** [comment]
Yes , is good , thank :-D

**Comment by eddyizm** [comment]
Moving this to a discussion so we can add it to documentation.
